#define IDC_MENU_CURSOR  100
#define IDR_TITLE_FONT   102
#define IDR_TITLE_DESC   104
#define IDR_TEXT_FONT    106
#define IDR_TEXT_DESC    108
#define IDR_MENU_ICONS        110
#define IDR_MENU_ICONS_ALPHA  112
#define IDR_RATIO_PREVIEW     114
